### ISSUE TITLE
Creation of .eseg files

### ISSUE THREAD

**Issue by Eisorak** [LSnyd/PartSegmentationToolbox#1]
Hello,
I would like to congratulate you for your work which is well explained and simplified.

On the other hand, I have a problem during the creation of the .eseg file.
When I execute the script extract_edge_labels.py on my 3D shape, it creates not only the .eseg file but also an .edges file.

The problem is that I get this error 
"Traceback (most recent call last):
  File "<blender_console>", line 7, in <module>
IndexError: list index out of range".

It creates me a 139 line .eseg file that's all.

Thank you to clarify me a little bit your code please.

**Comment by LSnyd** [comment]
Hi @Eisorak, 
I am happy hat you like my work! 

Could you check whether all existing vertices received a label? 
So if each one is assigned to one vertex group? 
You can easy check that by marking all vertices and then deseleting all existing vertex groups. 

I believe this error occurs, if that's not the case.

**Comment by Eisorak** [comment]
Hi @LSnyd 

yes I forgot 1 unassigned vertex, the problem is solved, thank you.
but I still didn't understand the principle of the .edge file.

**Comment by LSnyd** [comment]
Great!

The .edge file contains the vertices that define one edge. 
The number of the row stands for the edge ID.

I used those .edge files just for exploration. 
You don't necessarily need them to run MeshCNN or MedMeshCNN.

**Comment by Eisorak** [comment]
Okay!
thank you for your answers and your availability.

**Comment by Eisorak** [comment]
Hi @LSnyd 

I'm trying to create the .seseg files of my dataset with my own .seg and .obj files with your create_sseg.py code, but he creates seseg files that are not consistent so I checked the edges files he created and I noticed that they don't match with the edges of my mesh.
can i use my own edges files to create the seseg files?

thank you in advance

**Comment by LSnyd** [comment]
Hi @Eisorak, did you check that you "kept the order of the edges", when importing the object to Blender? 
You can use your own file, if it has the same structure.

**Comment by Eisorak** [comment]
I think I don't keep the same edges order, because my meshes are too big I didn't use blender for segmentation, I used another personal software to create my .seg and .edges files so when I run create_sseg.py, it creates a totally different .edges file, I think the order is not the same, so I want to work with my own .edges if it's possible.

**Comment by LSnyd** [comment]
If the order of the edges in the .edges file matches the order of the edges in your object file, it shouldn't be a problem.

**Comment by Eisorak** [comment]
Great!
how can I change your code please? can you direct me?
to not change the order of my mesh and not to create another .edges file.

**Comment by LSnyd** [comment]
Sorry, can't help you with that one. 

I don't really understand your issue though. If you change the edge order when importing the object into your personal software, just save a version of that object with the new edge structure and you should be fine.

**Comment by Eisorak** [comment]
the problem that in your code the def function "get_gemm_edges(faces, export_name_edges):" creates a new edges file and overwrites mine, so it changes the order of my edges, I removed this function but then I get errors.

**Comment by LSnyd** [comment]
This function takes the faces that are defined in the .obj file as a basis though. 
This should be the same approach that MeshCNN is taking. 

Therefore it seems like that the order of the edges of your .edges file does not correspond ing to the geometry in the object file. So you should somehow fit the object file to your edges file

**Comment by Eisorak** [comment]
Okay!
thank you very much for your answers.
