### ISSUE TITLE
Question: Repo maintenance

### ISSUE THREAD

**Issue by bensch98** [LSnyd/PartSegmentationToolbox#11]
Is this repo actively maintained and PRs appreciated?

I'm currently working on sth similiar in another domain and could improve it / make this toolbox much more user-friendly / automate few tasks during labeling.

Otherwise I'll just create a separate repo and reference you in it.

**Comment by LSnyd** [comment]
Hi @bensch98, 
this repo is not actively maintained, as I changed my research focus a bit. 
Feel free to start improving it in your own version. I can also reference your version in my readme if you link it here :)
