### ISSUE TITLE
Export results

### ISSUE THREAD

**Issue by Eisorak** [LSnyd/PartSegmentationToolbox#2]
Hi @LSnyd 

I executed your project MedMeshCNN, but I can't find the files that determine that each edge belongs to a certain class, because I would like to have the segmentation to visualize it with blender.
Is it possible?

Thanks

**Comment by LSnyd** [comment]
Hi @Eisorak, 
so are you looking for the segmentation results from MedMeshCNN?

Usually, those files should be in the /MedMeshCNN/checkpoints/../meshes/ folder. 
If you print one of the segmented files, you can find tall labels per edge just like this: 

```
....
e 10 303 1
e 9 302 3
e 450 449 3
e 449 457 3
e 4 443 3
e 212 298 3
e 306 833 3
```

You can plot them with the view.sh script provided in the script folders. 
Does that help?

**Comment by Eisorak** [comment]
Ah yes, I found it.
But there are 4 files for each .obj (name__1_0, name__1_1, name__1_2, name__1_3), can you explain me why please?

and

I want to open the file with blender not view.sh, is it possible?

**Comment by LSnyd** [comment]
Great! 
Each file belongs to one pooling layer. I believe name__1_3 is the output of the last pooling layer with the lowest resolution. 

I didn't write a script to view the file in Blender. 
It should work though, if you extract the edge labels from the name__1_0 file and use print_segmentation.py 
For the extraction of the labels, you might find some helpful code snippets in the upscale_labels.py file.

**Comment by Eisorak** [comment]
Okay!
Thank you very much for your answers, it's clear now.
I'm going to test what you just told me.

One more question, please,
You mentioned a mesh of 170,000 edges, but the meshes you shared are only about 2,500. Where can I download the 170,000 edge meshes you mentioned? so it will work on all mesh sizes?

**Comment by LSnyd** [comment]
No worries! 

Unfortunately, I can't publish the exact dataset I was using. 
However, part of the meshes came from the open source aneurisk dataset:
http://ecm2.mathcs.emory.edu/aneuriskweb/index

**Comment by Eisorak** [comment]
thank you really @LSnyd , you've made a lot of things clear to me.

**Comment by LSnyd** [comment]
No worries!

**Comment by liang3588** [comment]
> No worries!
> 
> Unfortunately, I can't publish the exact dataset I was using. However, part of the meshes came from the open source aneurisk dataset: http://ecm2.mathcs.emory.edu/aneuriskweb/index

So, how to download the dataset from the open source you provided?
