### ISSUE TITLE
choice of parameters

### ISSUE THREAD

**Issue by Eisorak** [LSnyd/PartSegmentationToolbox#3]
Hi @LSnyd 

I'm trying to adapt your segmentation architecture on my own data set which consists of 250,000 edges for each mesh, but I have a lot of errors.
Do I need to change the res_pool and convolution parameters? How do I choose the parameters please?

thank you

**Comment by LSnyd** [comment]
Hi @Eisorak, 
you have to change the parameters accordingly for instance 

input_edges should be set to 250.000 edges 
and for pooling it is best if you do not pool too many edges
so for instance [ 140.000, 100.000, 80.000 ] could work. 

Please check if the last pooling layer allows the MedMeshCNN to recognize any patterns though. 
Sometimes it's better to downsample, apply MedMeshCNN and then upsample the segmentation output to the original resolution.

**Comment by Eisorak** [comment]
thank you @LSnyd 
I'm gonna try this.

**Comment by LSnyd** [comment]
No worries. Feel free to also check the suggestions of the original MeshCNN implementation. 
These usually apply to MedMeshCNN as well.

**Comment by Eisorak** [comment]
hi @LSnyd 

I tried the res_pool at [ 140.000, 100.000, 80.000 ] but it gives me this error:
RuntimeError: CUDA out of memory. Tried to allocate 1.62 GiB (GPU 0; 8.00 GiB total capacity; 3.97 GiB already allocated; 1.25 GiB free; 4.68 GiB reserved in total by PyTorch).

Did you come across this error before?

but when I put small mesh it works perfectly.
