### ISSUE TITLE
Kernel and Convolution

### ISSUE THREAD

**Issue by Eisorak** [LSnyd/PartSegmentationToolbox#4]
hi @LSnyd 

I found the github of MeshCNN, I found the answer to many of my questions, thank you very much.
But I still have some questions that I haven't found the answer to yet.
if you allow me to answer please:

1) I saw that the kernel size for the convolution operation is 5, is it a vector or a matrix? and what is the result of the convolution? is it a matrix?

2) can you make me a simplified diagram of the convolution operation to understand the principle please?
because I'm used to images but I can't understand the reasoning for mesh.

**Comment by LSnyd** [comment]
Hi @Eisorak, 

I believe it starts of with the 5 features of the neighboring edges for each existing edge. Then you perform the General Matrix Multiplication to perform the convolution and perform edge pooling. As a result, you'll get the results for the 5 neighboring edges with their new feature maps for each edge. Could be something like this: 

![meshcnn_explain](https://user-images.githubusercontent.com/38072998/100750211-fb34c900-33e5-11eb-9a07-c2967f1e77f1.png)

Not sure if this is correct, this is also just my speculation :)

**Comment by Eisorak** [comment]
Hi @LSnyd 
thank you for your answer
