### ISSUE TITLE
length of vertex and faces

### ISSUE THREAD

**Issue by ziwenjie** [LSnyd/PartSegmentationToolbox#5]
hi @LSnyd
I run python create_sseg.py, but I got list assignment index out of range.
Does it depend on the length of seg, vertex and faces?  And what's the rule?

Thanks for your tool.

**Comment by LSnyd** [comment]
Hi @ziwenjie, 
It seems like your object file and the edges do not have the same amount of edges. 
Have you maybe forgotten to label edges within Blender? 
I usually double check that by marking all  edges and then deselecting all classes. If there are any edges left you need to add them to their class.

**Comment by ziwenjie** [comment]
Hi @LSnyd 
**Thanks for your suggestions.**

- Are the inputs of MeshCNN constant?  

- Have you ever marked large-scale mesh data, just like 
![image](https://user-images.githubusercontent.com/49607231/100743834-d3f6ef80-3417-11eb-8cb0-5c534bc33fcd.png)

**Comment by LSnyd** [comment]
You can change the input of MeshCNN by changing the n_input_edges in the config file  eg for training in  ./scripts/human_seg/train.sh

How many edges does your object have? I'd suggest to downsample anyway for computational efficiency. 
When you have the segmentation result, you can use the scripts of the PartSegmentationToolbox to upscale the results to the original resolution. What do you mean by marked?

**Comment by ziwenjie** [comment]
- My object have tens of thousands edges, and the number is unfixed.

- I mean that did you have the large-scaled marked mesh data 😜？

- “It seems like your object file and the edges do not have the same amount of edges.”
It is not the same amount of coseg_vases' edges.

**Comment by LSnyd** [comment]
It doesn't matter whether it is not the same amount of edges as in coseg_vases. 
As long as the edge amount within the .obj file and the .edge file are the same, a correct .seseg file should be created. 
If you then define the correct number as input edges for MeshCNN, everything should be working.

**Comment by ziwenjie** [comment]
I see, how to get the edge amount of .obj file? 😜

**Comment by LSnyd** [comment]
Just check your .obj file in Blender

**Comment by ziwenjie** [comment]
Thanks @LSnyd 
I see.😁👍
Thanks again!

**Comment by LSnyd** [comment]
No worries @ziwenjie :)
