### ISSUE TITLE
 I want to know how to label it.

### ISSUE THREAD

**Issue by Pkae** [LSnyd/PartSegmentationToolbox#6]
I labeled it with the prepare_blender.py script and even colored it
It seems that the coordinate values ​​labeled in vertices in the extract_edge_labels.py script cannot be retrieved. I think the labeling method is wrong, can you tell me in detail how to label it?

**Comment by LSnyd** [comment]
Hey there, 
did you label your object within Blender as described in my Medium article [here](https://medium.com/@lisa_81193/how-to-perform-a-3d-segmentation-in-blender-2-82-d87300305f3f)?

**Comment by Pkae** [comment]
When I run the script exporting to .esg because I think I followed it well, I get IndexError: list index out of range T.T

**Comment by Pkae** [comment]
If I import it as .stl, does the labeling work well?

**Comment by Pkae** [comment]
Sorry, I solved this problem
I misinterpreted English

Have a nice day :)

**Comment by LSnyd** [comment]
Great, I am glad you solved your problem!
