### ISSUE TITLE
creat_sseg.py There is an error. Help TT

### ISSUE THREAD

**Issue by Pkae** [LSnyd/PartSegmentationToolbox#7]
I have a new issue, so I ask again T T

I am trying to convert a seg file with the creat_sseg.py script

IndexError: index 29 is out of bounds for axis 0 with size 15
I get an error

In my short opinion, it seems to be an error caused by entering more data than the length of the array. Can I increase the length of the array?

**Comment by LSnyd** [comment]
Hey there, 
have you double checked, if you labelled all available edges within the .obj file in Blender? 
I usually mark all edges and then deselect each group to see if there are any edges left.

**Comment by Pkae** [comment]
Selecting and labeling the entire obj file gave me an error.

Interestingly, not all files have errors, only some files have errors

**Comment by LSnyd** [comment]
That's not what I meant. Select the entire obj file in Blender and then deselect all vertex groups that you defined. 
Then check if there are any edges left. If there are any edges left, add them to one of your classes.

**Comment by Pkae** [comment]
understand. Let's try it.

**Comment by Pkae** [comment]
Has confirmed. I have checked that there is nothing left on the edges, and the other thing I want to ask is the create_sesg.py script does not work if there are spaces between the labeling numbers (vertex groupe) (ex 1, then group 3). Is this intended?

**Comment by Pkae** [comment]
Create_sesg.py didn't work if group 1 was assigned, skip 2 and group 4 or 5 were assigned.

**Comment by LSnyd** [comment]
Yeah that's intended! I am glad you figured it out :)
